version: '3'

services:

  mongodb:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dev@mobile.com
    ports:
      - "27017:27017"

  mongoclient:
    image: mongoclient/mongoclient
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb